- hosts: all
  become: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
    - name: Install python
      apt: name=python state=latest

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: add group
      user: name=vagrant groups=docker append=yes
      tags: dockerhost
      become: True

    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: ensure docker-compose is installed and available
      get_url:
        url : https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_machine}}
        dest: /usr/local/bin/docker-compose
        owner: vagrant
        group: vagrant
        mode: 'u+x,g+x'
    
    - name: Install minikube
      become: yes
      become_user: vagrant
      shell: "{{ item }}"
      with_items:
        - 'sudo curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64'
        - 'sudo chmod +x minikube'
        - 'sudo mkdir -p /usr/local/bin/'
        - 'sudo install minikube /usr/local/bin/'
    
    - name: Install kubectl    
      become: yes
      become_user: vagrant
      shell: "{{ item }}"
      with_items:
        - 'sudo curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"'
        - 'sudo chmod +x kubectl'
        - 'sudo mv kubectl /usr/local/bin/kubectl' 